# Generated by Django 4.2.26 on 2025-11-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_hat_no', models.IntegerField()),
                ('alt_hat_no', models.IntegerField()),
                ('ana_hat_adi', models.CharField(max_length=255)),
                ('alt_hat_adi', models.CharField(max_length=255)),
                ('durak_sayisi', models.IntegerField(blank=True, null=True)),
                ('uzunluk_km', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('ana_hat_no', 'alt_hat_no')},
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalkis_tarihi', models.DateTimeField()),
                ('tarife_tipi', models.CharField(max_length=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bus.busline')),
            ],
        ),
    ]
