# Generated by Django 4.2.26 on 2025-11-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yon', models.CharField(blank=True, max_length=10, null=True)),
                ('sira', models.IntegerField()),
                ('enlem', models.FloatField()),
                ('boylam', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bus.busline')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
    ]
