# Generated by Django 4.2.26 on 2025-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_busroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='tarife_tipi',
            field=models.CharField(max_length=50),
        ),
    ]
