# Generated by Django 4.2.26 on 2025-11-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_busschedule_tarife_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durak_no', models.CharField(max_length=50)),
                ('sira', models.IntegerField()),
                ('istikamet', models.CharField(blank=True, max_length=255, null=True)),
                ('enlem', models.FloatField(blank=True, null=True)),
                ('boylam', models.FloatField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bus.busline')),
            ],
        ),
    ]
